//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_CallPHPSOAP.MyPHPServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:myTns", ConfigurationName="MyPHPServer.MyPortType")]
    public interface MyPortType {
        
        // CODEGEN: 作業 SumData 未由 RPC 或文件所包裝，正在產生訊息合約。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CS_CallPHPSOAP.MyPHPServer.SumDataResponse SumData(CS_CallPHPSOAP.MyPHPServer.SumDataRequest request);
        
        // CODEGEN: 作業 SubData 未由 RPC 或文件所包裝，正在產生訊息合約。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CS_CallPHPSOAP.MyPHPServer.SubDataResponse SubData(CS_CallPHPSOAP.MyPHPServer.SubDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int Sum_a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int Sum_b;
        
        public SumDataRequest() {
        }
        
        public SumDataRequest(int Sum_a, int Sum_b) {
            this.Sum_a = Sum_a;
            this.Sum_b = Sum_b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Sum_Result;
        
        public SumDataResponse() {
        }
        
        public SumDataResponse(string Sum_Result) {
            this.Sum_Result = Sum_Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int Sub_a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int Sub_b;
        
        public SubDataRequest() {
        }
        
        public SubDataRequest(int Sub_a, int Sub_b) {
            this.Sub_a = Sub_a;
            this.Sub_b = Sub_b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Sub_Result;
        
        public SubDataResponse() {
        }
        
        public SubDataResponse(string Sub_Result) {
            this.Sub_Result = Sub_Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyPortTypeChannel : CS_CallPHPSOAP.MyPHPServer.MyPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyPortTypeClient : System.ServiceModel.ClientBase<CS_CallPHPSOAP.MyPHPServer.MyPortType>, CS_CallPHPSOAP.MyPHPServer.MyPortType {
        
        public MyPortTypeClient() {
        }
        
        public MyPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CS_CallPHPSOAP.MyPHPServer.SumDataResponse CS_CallPHPSOAP.MyPHPServer.MyPortType.SumData(CS_CallPHPSOAP.MyPHPServer.SumDataRequest request) {
            return base.Channel.SumData(request);
        }
        
        public string SumData(int Sum_a, int Sum_b) {
            CS_CallPHPSOAP.MyPHPServer.SumDataRequest inValue = new CS_CallPHPSOAP.MyPHPServer.SumDataRequest();
            inValue.Sum_a = Sum_a;
            inValue.Sum_b = Sum_b;
            CS_CallPHPSOAP.MyPHPServer.SumDataResponse retVal = ((CS_CallPHPSOAP.MyPHPServer.MyPortType)(this)).SumData(inValue);
            return retVal.Sum_Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CS_CallPHPSOAP.MyPHPServer.SubDataResponse CS_CallPHPSOAP.MyPHPServer.MyPortType.SubData(CS_CallPHPSOAP.MyPHPServer.SubDataRequest request) {
            return base.Channel.SubData(request);
        }
        
        public string SubData(int Sub_a, int Sub_b) {
            CS_CallPHPSOAP.MyPHPServer.SubDataRequest inValue = new CS_CallPHPSOAP.MyPHPServer.SubDataRequest();
            inValue.Sub_a = Sub_a;
            inValue.Sub_b = Sub_b;
            CS_CallPHPSOAP.MyPHPServer.SubDataResponse retVal = ((CS_CallPHPSOAP.MyPHPServer.MyPortType)(this)).SubData(inValue);
            return retVal.Sub_Result;
        }
    }
}
